name: Generate Snake
on:
  schedule:
    - cron: "0 */6 * * *"  # Roda a cada 6 horas
  workflow_dispatch:  # Permite rodar manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Vers達o atualizada
      - name: Generate snake
        uses: Platane/snk@v3  # Vers達o atualizada
        with:
          github_user_name: ezequias  # Seu user
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v4  # Vers達o atualizada
        with:
          target_branch: output
          build_dir: dist
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4  # Vers達o atualizada
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
